#!/bin/bash
set -e

psql -tc "SELECT * FROM pg_roles WHERE rolname='${POSTGRES_USER_FOR_DB}'" | grep -q 1 || psql -tc "CREATE USER ${POSTGRES_USER_FOR_DB} WITH PASSWORD '${POSTGRES_PASSWD_FOR_USER}'";

psql <<- EOSQL

    ALTER USER ${POSTGRES_USER_FOR_DB} WITH PASSWORD '${POSTGRES_PASSWD_FOR_USER}';
    ALTER USER postgres WITH PASSWORD '${POSTGRES_PASSWORD}';
    ALTER USER ${POSTGRES_USER_FOR_DB} WITH VALID UNTIL 'infinity';
    ALTER USER ${POSTGRES_USER_FOR_DB} WITH SUPERUSER;

EOSQL

echo "Created user ${POSTGRES_USER_FOR_DB}"
