#!/bin/bash
set -e

echo "Update packages..."
apt-get update
echo "Install required packages..."
apt-get install -y --no-install-recommends ca-certificates wget
su - postgres --preserve-environment /usr/local/bin/_import_data $@
apt-get purge -y --auto-remove wget ca-certificates
rm -rf /var/lib/apt/lists/*
