#!/bin/bash
set -e

apt-get update
apt-get install -y --no-install-recommends libgdal-dev git
git pull origin ${DJANGO_REPO_BRANCH}
git log -n2
pip install -r requirements.txt
apt-get purge -y --auto-remove git
rm -rf /var/lib/apt/lists/*

echo "Django updated"
